<a href="https://colab.research.google.com/github/stutis28/IntroductionToDataScience/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
myList = [1, 2, 3]
x = np.array(myList)
x

array([1, 2, 3])

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [5]:
m = np.array([[1, 2, 3], [10, 11, 12]])
m

array([[ 1,  2,  3],
       [10, 11, 12]])

In [7]:
m.shape

(2, 3)

In [8]:
# start, stop, step
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
# reshape an array
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [12]:
# linspace range of numbers split according to the step
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [15]:
# resize to change the dimensions
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [16]:
# returns an array of "1's"
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# returns an array of "0's"
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# returns an array with diagonals as "1's"
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# constructs a diagonal array
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [25]:
# repeat arrays in two ways
# 1:
repeat_one = np.array([1, 2, 3] * 3)
print(repeat_one)

# 2:
repeat_two = np.repeat([1, 2, 3], 3)
print(repeat_two)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [26]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [27]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [29]:
np.hstack([p, 3*p])

array([[1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3]])

Operation

In [30]:
x + y

array([5, 7, 9])

In [31]:
x * y

array([ 4, 10, 18])

In [32]:
x**2

array([1, 4, 9])

In [33]:
x.dot(y)

32

In [34]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [35]:
z.shape

(2, 3)

In [36]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [37]:
z.T.shape

(3, 2)

In [38]:
z.dtype

dtype('int64')

In [40]:
z = z.astype('f')
z.dtype

dtype('float32')

Mathematical Functions on array

In [0]:
a = np.array([-4, -2, 1, 3, 5])

In [42]:
a.sum()

3

In [43]:
a.max()

5

In [44]:
a.min()

-4

In [45]:
a.mean()

0.6

In [46]:
a.std()

3.2619012860600183

In [47]:
# index of max or min value
a.argmax()

4

In [48]:
a.argmin()

0

Indexing / Slicing

In [50]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [51]:
# start : stop
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [53]:
# counting 5th from the end till the start of the array and 
# counting by 2
s[-5::-2]

array([64, 36, 16,  4,  0])

In [54]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [55]:
r[2,2]

14

In [56]:
r[3, 3:6]

array([21, 22, 23])

In [57]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [58]:
r[-1, ::2]

array([30, 32, 34])

In [60]:
r[r > 30] = 30 
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [61]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [62]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [64]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Iterate over arrays

In [65]:
test = np.random.randint(0,10, (4, 3))
test

array([[4, 0, 8],
       [2, 8, 1],
       [4, 0, 3],
       [1, 2, 7]])

In [66]:
for row in test:
  print(row)

[4 0 8]
[2 8 1]
[4 0 3]
[1 2 7]


In [68]:
for i in range(len(test)):
  print(test[i])

[4 0 8]
[2 8 1]
[4 0 3]
[1 2 7]


In [69]:
for i, row in enumerate(test):
  print('row', i, 'is', row)

row 0 is [4 0 8]
row 1 is [2 8 1]
row 2 is [4 0 3]
row 3 is [1 2 7]


In [70]:
test2 = test ** 2
test2

array([[16,  0, 64],
       [ 4, 64,  1],
       [16,  0,  9],
       [ 1,  4, 49]])

In [72]:
for i, j in zip(test, test2):
  print( i , '+', j, '=', i+j)

[4 0 8] + [16  0 64] = [20  0 72]
[2 8 1] + [ 4 64  1] = [ 6 72  2]
[4 0 3] + [16  0  9] = [20  0 12]
[1 2 7] + [ 1  4 49] = [ 2  6 56]


In [73]:
type(lambda x:x+1)

function

In [74]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [0]:
r = np.arange(36)

In [76]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [77]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [78]:
r[:,::7]

IndexError: ignored

In [79]:
r[0:6,::-7]

IndexError: ignored

In [80]:
r[::7]

array([ 0,  7, 14, 21, 28, 35])